- name: Install base packages
  apk: name={{ item }} state=present
  with_items:
    - ucarp
    - net-tools
    - sysstat
    - wget

- name: Update sshd_config
  lineinfile:
    path: /etc/ssh/sshd_config
    state: present
    line: "{{ item }}"
  with_items:
    - 'AllowAgentForwarding yes'
    - 'AllowTcpForwarding yes'
    - 'GatewayPorts yes'
    - 'UseDNS no'
  notify:
  - restart sshd 
