- name: Install python minimal
  raw: apt-get install python-minimal aptitude -y
  when: ansible_pkg_mgr == 'apt'

- name: Install epel-release
  raw: yum -y install epel-release
  when: ansible_pkg_mgr == 'yum'

- name: Install base packages
  package: name={{ item }} state=present
  with_items:
    - net-tools
    - sysstat
    - vim
    - wget
  tags:
    - packages

- name: Update /etc/hosts file
  lineinfile:
    dest: /etc/hosts
    state: present
    line: "{{ item }}"
  with_items:
    - '10.0.0.30        pve'
    - '10.0.0.31        pve1'
    - '10.0.0.32        pve2'
    - '10.0.0.33        pve3'
    - '10.10.10.30        pve.cls'
    - '10.10.10.31        pve1.cls'
    - '10.10.10.32        pve2.cls'
    - '10.10.10.33        pve3.cls'
    - '10.0.0.40        ctu1800 ctu1800-ansible'
    - '10.0.0.41        ctu1801'
    - '10.0.0.42        ctd802'
    - '10.0.0.43        ctc703'
    - '10.0.0.50        vmc700  vmc700-ansible'
    - '10.0.0.51        vmc701'
    - '10.0.0.52        vmc702'
    - '10.0.0.53        vmc703'
    - '10.0.0.26        hadoop01'
    - '10.0.0.27        hadoop02'
    - '10.0.0.28        hadoop03'
    - '10.0.0.29        hadoop04'

- name: Update /root/.ssh/authorized_keys
  lineinfile:
    dest: /root/.ssh/authorized_keys
    state: present
    line: "{{ item }}"
  with_items:
    - 'ssh-rsa AAAAB3NzaC1yc2EAAAABJQAAAQEA3PzWlJGIZ94yqcXPKSrL/vxhTiO5SjDtgrB08qVnA4OWQs/ll+U9LvMcaLtNfJyRbXidbQJPDzZNftKkqS2G2CnHOlPvNHleTjCu0aqz/IeAq/jBXWY9PGWGoXtduJteILrlY97AjNzD2u3asgZV2NDIl9qFjBP5G0p2QUEmck1k8T8/arLHqn3vmWK7W5ta0dJZmYTkySF/e7nbzu7kkI6skdtZtaWdRe86O4ckF5XASXVnN5pr34uUxmBBxAjsSS1OA9W+ydbbTwI+ziXA8ER5yJMZUBYxuGQI7vXfcheproXho+dh114SAIPx6bMQKX1WinYA2kxuo4tF/E9bEw== rsa-key-20180609'
    - 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCfq/3t86J4QKOBnmj0xIW013tS2i5Hq6s4pkjo0lOgjI28EOGmoUkIMccv9Wx7382TaZR42+0hiDz5qpJttwA5QjZUDORqH1evY1uhPgQWhD1vcBOiySVVU7X3dfcWjF9CWCnRrAnxcz+XO9ubOHta1+Vle/MJWolcaE1uzDkSgWRYVjMLA7cFRkuPuzwxOW9+JSv6UJec80NLc/FG8FRT5n2mguqUkXHHEVAWmQ6LvFvU1UykcyTXQEgDH3F5tmAQEu/l3Dku3MTxD9zvYCnNEsn7JDqq9i/JgWqqV16X0R7TEBevu2WVgHY5acThHjBUtbp7YMb3wVHTPTPPg4jZ root@vmu1800'
    - 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQD2emeGDlV8NPLG8BNhlq1HEzwW3sRaxP7hss+eLopTZYIP/5l4N4a8kRPkOW/CeuJP1w2yExi583OH6ZUQbNAm6G0rKNipyEAA0ERypNzhEvZSsx4AaHJGnh5u51nOrERvl4pM3t7Pi0BY36jC6k767ODcogrrttVwgcqibhJk6MWEnHv7gD5J3DbSuVXcQV+rBvsFjRiy839p601nx+ifkYJyAvNV4ThEDW+RV1P24tSxNx7/d3Eij5662+26ZP/LbMK9TL5ndDivQavYAw3fKhRmNeJfRwAKvZZiibF+BfdRrzN4v/2HM1WuH9ONTqwVyN7nsNiiW38E50WaUKaf peter@Peters-MacBook-Pro.local'
    - 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC6ihNPJgarBSJ86ITZtWf7nnmbv4AVtMWyQMC15JJslIIYosWk+/Io/dNUCYhpMSpwpHGCEkxROSXF3nxO8t+8dLYVOXviKeriE+dAGUp5DAIVsadyObbnTJxmnwSvPdzC9Zz+l1lYSpbTVXuf979UWkTMaiJq3GgWDILH72mywTPbevgatG0ilA7cezyUnPE6iSTygLQ1lCDlOH2TCvUyywEr2zHkRhWMHZDXxBhwRLZ6TkA1XSpeXJRYz1VWwBDnS9cexDzrE/qCT7FibW47SNDLu/DWpEQ5QtZ+H3+VySb7kXo9Z+xiK1DpDSZGiH7wSMvnYyuMsvRAwiffhjHl root@NA123'
    - 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC/Dr4X0FDnutyvhRwlWmXmJ0r3aoQNESL2Q40Rg6ynM5xG8xF05O8fUCYO2XhpJBdxhsxsEugPIyMdd4iWXmbQKuqAyQGg3IcOh7HDinkB6pqtTcGnFQx6h3y0MYTbOj18mpt6JtDgL1TzPCb4hia3nSTS3nbvyB/P6vKEljUzxa0fgTxf3spfAGnGku37mewWasDdIVKMo1BQIbihYGMsAHjvpaxs9O8NZHgIXi+6c6EM/KLdu1ZGgINsy9UOpbl1SGPW3HEkfuX0g93S2d4Hh2zf8VekFJJ959y4J1wHZ5Ab8r6Yz2eGTfGJ5bzW1hjQR3Ci4snAg8/+zPsjRSpp root@pve'
    - 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC0hzVI+Ow6BXNjPY72O6rlnlEAistD6CrFEBhyngXR1WWrAh7C5HIgUtatxwDnl5RG/q0ogTrJKc8fgPmh301KHHJwhu9B0gpzH2zZzxyAU+RFOnVO2XvY4tZx7g+3TmL+j8qwSnxXGDAr3y3TTm/6zDHEUnrsV/foxLx+45C/pSWPo5i+N/Rwg+JrI4thZiGQY4cuMMOFO7NRHksNMaBEJmnuv0m1HbVNhumHCm230Zc+k01Z6f4eoM+XOKZ+6beMapSZFSaWa4ogfvqjdF0mt1QNCbpdrgZm9x0QJnGBrWjr6EjaTzDSwrETs2zuna/nq3USv1DIPA2Ixp02UurR root@pve1'
    - 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC9I7Pdkxg6SyqJoDVNQ2KMAmUNXz9mdniRq0JjfTbUgNVVTNZQ0nD6CffxDKcYD6GWllRDr3TgtYJbDjqAMuktxzOcie3iaCKzEEefpu+/hA1UohN7Aj4oRu7GzrphcH0RkkB8WQPdT96p6a/MuNCTHGBb8PO271CeyO/6ZxgpI5cDfLLJYlfk5VMUAG+jKX4VJrzZG8+eg5JCLoCr+VVVWB3/83H3ti2N6mD4pkeoUPRG9rtfhVBrMo2eaA+KbEzqnOjSNFJd5//qYXxrO5oKf/6PLvOff0/dh2lqszA/brvLb9pTCkFxsjvrViDkWbDotC48Gtse1qmZVPqNKPgN root@pve2'
    - 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDClxMUNgXaR9FHh8EnNuEHBGRsAm4aoNU9oYU36fg8IL49Jk6lClbFQ5uuV0Iq5Yo/9yGZNNYCEb5bO5fHFIxIrG90FNoDi3uIFWCBNJjiF6RDteZjt19qyhY5prHXRmWjgqMhRE0IgXZZy+HuOyZ8BNEb5QCIxKxn+/0/QBn0ygP8LvdLDfU3ornYjCzFYPupOu+zuyKwPTj7CsPS0jniZHEShllkYMsSynMARQFBi5mxB5KRkSr07dskrp2InfLo9CWMhIY9JulMF/uH1jmPqyN52ej3N1lRA15G90s9riVCHyxBodW6V0qcqvcGnVcw4DqnDN5QkZkwog+FgyWz root@pve3'

- name: Update profile
  lineinfile:
    dest: /etc/profile
    state: present
    line: "{{ item }}"
  with_items:
    - 'set -o vi'
    - 'alias vi=vim'
    - 'export EDITOR=vi'

- name: Update sshd_config
  lineinfile:
    path: /etc/ssh/sshd_config
    state: present
    line: "{{ item }}"
  with_items:
    - 'AllowAgentForwarding yes'
    - 'AllowTcpForwarding yes'
    - 'GatewayPorts yes'
    - 'UseDNS no'
    - 'PermitRootLogin yes'
  notify:
  - restart sshd 
