- name: Update /etc/hosts file
  lineinfile:
    dest: /etc/hosts
    state: present
    line: "{{ item }}"
  with_items:
    - '10.0.2.1        pve1'
    - '10.0.2.2        pve2'
    - '10.0.2.3        pve3'
    - '10.0.2.4        pve4'
    - '10.0.2.5        pve5'
    - '10.0.2.6        pve6'
    - '10.1.2.1        pve1.cls'
    - '10.1.2.2        pve2.cls'
    - '10.1.2.3        pve3.cls'
    - '10.1.2.4        pve4.cls'
    - '10.1.2.5        pve5.cls'
    - '10.1.2.6        pve6.cls'

- name: Update /root/.ssh/authorized_keys
  lineinfile:
    dest: /root/.ssh/authorized_keys
    state: present
    line: "{{ item }}"
  with_items:
    - 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDODT+W/+tMTEyt0kjyILbaiYyHejvnjxfhvfpAlN6iyOXWN/iAf+k8AREFRLunP5hstOCw0N2NOyp0PgyMNivG0J3TqQwQLAhuoI2gM5A/1Ri8mTdsb34K5UGmc67gu5dUe3zpXK3EMey6S3EZR2Pd5ixuNWwvI86dzgX7miBBdZCp6h41EMUTV/mNvT2p7yuKYfvy9ZuKPLXOy0/kH4R9j1uL8AgO7y6W+pQKYIRZWSPNL1KDG9QEYS337/s14anMMI8Es5CoTE/40FLLJe86BD7573MtyhrUHH67+7xFuj0K/MbOYf8Q8bOnuS6VBMdlNa3HxyRHr/O7E36gjLvl peter@Peters-iMac.local'
    - 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDnd2zFavifiaSIX3DLhHRBS6nsgA2NpofO0h5u9Bo6t2RkkqTidCvm1dT9zGB4wO9elPNlYnC+oR7C8f9c/eofD+fRsU4VkByRN29ewQr7sBvQtjXFP6jDr+hU2Zia0p7GLnskjHhr0tjOiYBdC+56bpducOZIWgfrlNlAAIDmNm1KrNxpMcFOwp3a+r9+WEYaTojuF/2k1yNobkVHmWH+zINvYvm8Nl3xeQANgqdAMlbKRCTwj/ayXuRAQgVaXXGcTeldlKL4/iE31jx44EM+di5zm5tOOI2nZmzUIAqpl2gQV1sCCL5TzL0kke07S+X+95QWLvOPRJjY9dE8/Ng7 root@pve4'
    - 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDNLRKrgc1IUjFMYHsgbjOZd+CwmXdgMt9yQ+bAin5H7ae6Yd795pjeAC6q6T2m1LdspvYXe2H+BXVEDTTrz6DTacpHDM7hMW6KpZtLetTgtUZyrTDey4VPtR0wz94sFhhamvCQVgcjmX6s65Rs9QBzagNpd90EaZbw7TykWfQXdYHxVvCjShHmkePKVW9w6hgn7phTZ3eUV5Qybz0FSzapK2bM9zPFjuOFSlrinQ1V6oBvuyThgQ/g7SCwelRwilApeQDFu9B2ebZ3XH46KnQBVZ250B4BsbmHrmiC9JtUqwPiKV7fLkIWUmtJFEXE+lno6kCJk8J4ARZfUrLAZMXT root@pve5'
    - 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDOlp/bCFDNDmhdaAgEcA4nO3Qh9fYJzNCltJRUTCCO7EnkpqNKL674MbJme39LWFwfGJ1WJehZTDuDXlnozl9s0LW4VVA6MG9GXtmsUlF6YT+tvQdhJSlmHq7x6GO8/q07MLQ8cRWRzkGHKqpqZTClfwpzgavc1+bfK551kW2No3vo3kHyyPa9aIe6+46Ma9zw39ezJWio3ZLM9RspH/2zrtpu7JgSUTAayrEOlT8sXrMtgUNXSe+2GnO7h9z8ZC9JJzKfqIrEFli2V8qTodijfHAjGNUqu9tt0+zUsUg/vssxLx/a8N/dYXfL2r/FNMy7TDc/gP3egA6n4LaMhEJn root@pve6'

- name: Update profile
  lineinfile:
    dest: /etc/profile
    state: present
    line: "{{ item }}"
  with_items:
    - 'set -o vi'
    - 'export EDITOR=vi'
- name: remove vim
  lineinfile:
    dest: /etc/profile
    state: absent
    regexp: 'alias vi=vim'
#- name: Add bash profile
#  lineinfile:
#    dest: /root/.bash_profile
#    state: present
#    line: "{{ item }}"
#  with_items:
#    - 'export PS1="\u@\h \e[32m\w \e[1m\e[93m\$(git branch 2>/dev/null | grep '^*' | colrm 1 2)\e[00m$ "'
